### ISSUE TITLE
🔥🔥NEW ISSUE TEMPLATE: Please use and edit as necessary🔥🔥

### ISSUE THREAD

**Issue by mannyrules** [petermr/CEVOpen#18]
Putting on my project manager's hat ⛑, I just set up a [Kanban-style](https://en.wikipedia.org/wiki/Kanban) project card structure [here](https://github.com/petermr/CEVOpen/projects/1). Please bookmark it and set it as your main page.

Also, Please use the template below for each new Issue you open. Aim to complete it such that any reader can be clear about the issue's purpose and importance, and perhaps find ways we can assist you in it. Thanks!

# The Big WHY

**We are building AMI so that:**
Type of User: 
can: 
without: 

**Goals:**
_Describe the Challenge, the solution we will bring, and the Desired End State by which all will know we have achieved excellence._
* A. 
* B. 
* C. 

**Desired Results:**
_A clear and concise description / outline of the final "state or vision" of the project — the evidence we will see when our goals are achieved._
* A. 
* B. 
* C. 

**Guiding principles:**
_What principles will guide our decisions as we do our part to fulfill the mission?_
* A. 
* B. 
* C. 

**Massive Action Steps:**
_What massive actions will generate the Desired Results?_
* A. 
* B. 
* C. 

**Responsibilities and Roles:**
_Who will have what completed when?_

**Interim Deliverable #1:** 
* Milestone: 
* Milestone Date: 
* Single Individual Responsible for ensuring this Milestone is reached on time:

**Interim Deliverable #2**
* Milestone: 
* Milestone Date: 
* Single Individual Responsible for ensuring this Milestone is reached on time:

**Tips, Tools, Shortcuts and Resources:**
_Anything done or used to make the desired outcome more likely to occur._
* A. 
* B. 
* C. 

**Rules and Responsibilities for Achieving Excellence**
**_Always:_**
* A. 
* B. 
* C. 

**_Never:_**
* A. 
* B. 
* C.

**Comment by ambarishK** [comment]
# The Big WHY?

**We are building AMI so that:**
Type of User: ______________________
can: _____________
without: _________

**Goals:**
_Describe the Challenge, the solution we will bring, and the Desired End State by which all will know we have achieved excellence._
* A. 
* B. 
* C. 

**Desired Results:**
_A clear and concise description / outline of the final "state or vision" of the project — the evidence we will see when our goals are achieved._
* A. 
* B. 
* C. 

**Guiding principles:**
_What principles will guide our decisions as we do our part to fulfill the mission?_
* A. 
* B. 
* C. 

**Massive Action Steps:**
_What massive actions will generate the Desired Results?_
* A. 
* B. 
* C. 

**Responsibilities and Roles:**
_Who will have what completed when?_

**Interim Deliverable #1:** 
* Milestone: 
* Milestone Date: 
* Single Individual Responsible for ensuring this Milestone is reached on time:

**Interim Deliverable #2**
* Milestone: 
* Milestone Date: 
* Single Individual Responsible for ensuring this Milestone is reached on time:


**Tips, Tools, Shortcuts and Resources:**
_Anything done or used to make the desired outcome more likely to occur._
* A. 
* B. 
* C. 

**Rules and Responsibilities for Achieving Excellence**
**_Always:_**
* A. 
* B. 
* C. 

**_Never:_**
* A. 
* B. 
* C.

**Comment by petermr** [comment]
Not immediately relevant to CEV strategy
